apiVersion: v2
name: medici-chart
description: A Helm chart for Kubernetes
type: application
version: 0.1.1
appVersion: 0.1.0
dependencies:
    - name: chainlink
      version: 0.1.0
      condition: chainlink.enabled
    - name: geth
      version: 0.1.0
      condition: geth.enabled
    - name: awslambda
      version: 0.1.0
      condition: awslambda.enabled
    - name: nginx-ingress
      version: 1.30.1
      repository: "@stable"
      condition: nginx-ingress.enabled
    - name: postgresql
      version: ~8.3.0
      repository: "@stable"
      condition: postgresql.enabled
    - name: pgadmin
      version: ~1.1.4
      repository: "@stable"
      condition: pgadmin.enabled
    - name: kubeapps
      version: ~3.3.1
      repository: "@bitnami"
      condition: kubeapps.enabled